apiVersion: v1
kind: Pod
metadata:
  name: "backbeat-test-pod"
spec:
  activeDeadlineSeconds: 3600
  restartPolicy: Never
  terminationGracePeriodSeconds: 10
  containers:
  - name: aggressor
    image: {{ images.aggressor }}
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    command: ["/bin/sh", "-c", "buildbot-worker create-worker . ${BUILDMASTER}:${BUILDMASTER_PORT} ${WORKERNAME} ${WORKERPASS} && buildbot-worker start --nodaemon"]
  - name: mongo
    image: scality/ci-mongo:3.6.8
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 1Gi
  - name: redis
    image: redis:alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 1Gi
