---
apiVersion: v1
kind: Pod
metadata:
  name: worker
spec:
  containers:
    - name: unit-and-feature-tests
      image: "{{ images.unit_and_feature_tests }}"
      resources:
        requests:
          cpu: "250m"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 1Gi
      volumeMounts:
        - name: workspace
          mountPath: /home/eve/workspace
  volumes:
    - name: workspace
      emptyDir: {}
